<?php
namespace App\Supports;
class Constants {
    const NON_SPPD = "NON_SPPD";
    const PERJALANAN_DINAS_BIASA="PERJALANAN_DINAS_BIASA";
    const PERJALAN_DINAS_DALAM_KOTA="PERJALAN_DINAS_DALAM_KOTA";
    const PERJALANAN_DINAS_LUAR_KOTA="PERJALANAN_DINAS_LUAR_KOTA";
    const PERJALANAN_DINAS_PAKET_MEETING="PERJALANAN_DINAS_PAKET_MEETING";
    const JENIS_SURAT_TUGAS_OPTIONS = [
        "NON_SPPD" => "Non SPPD",
        "PERJALANAN_DINAS_BIASA" => "Perjalan Dinas Biasa",
        "PERJALANAN_DINAS_LUAR_KOTA" => "Perjalanan Dinas Luar Kota",
        "PERJALAN_DINAS_DALAM_KOTA" => "Perjalanan Dinas Dalam Kota",
        "PERJALANAN_DINAS_PAKET_MEETING" => "Perjalanan Dinas Paket Meeting",
    ];

    const NON_TRANSPORTASI = "NON_TRANSPORTASI";
    const TRANSPORTASI_KENDARAAN_UMUM = "TRANSPORTASI_KENDARAAN_UMUM";
    const TRANSPORTASI_KENDARAAN_DINAS = "TRANSPORTASI_KENDARAAN_DINAS";
    const JENIS_TRANSPORTASI_OPTIONS = [
        "NON_TRANSPORTASI" => "-",
        "TRANSPORTASI_KENDARAAN_UMUM" => "Kendaraan Umum",
        "TRANSPORTASI_KENDARAAN_DINAS" => "Kendaraan Dinas",
    ];
    const STATUS_PENGAJUAN_DIKIRIM = "STATUS_PENGAJUAN_DIKIRIM";
    const STATUS_PENGAJUAN_BUTUH_PERBAIKAN= "STATUS_PENGAJUAN_BUTUH_PERBAIKAN";
    const STATUS_PENGAJUAN_DIBATALKAN = "STATUS_PENGAJUAN_DIBATALKAN";
    const STATUS_PENGAJUAN_DITOLAK = "STATUS_PENGAJUAN_DITOLAK";
    const STATUS_PENGAJUAN_DITERIMA = "STATUS_PENGAJUAN_DITERIMA";
    const STATUS_PENGAJUAN_DIBUAT= "STATUS_PENGAJUAN_DIBUAT";
    const STATUS_PENGAJUAN_DIKUMPULKAN = "STATUS_PENGAJUAN_DIKUMPULKAN";
    const STATUS_PENGAJUAN_DICAIRKAN = "STATUS_PENGAJUAN_DICAIRKAN";
    const STATUS_PENGAJUAN_OPTIONS = [
        "STATUS_PENGAJUAN_DIKIRIM"=>"Dikirim",
        "STATUS_PENGAJUAN_BUTUH_PERBAIKAN"=>"Butuh Perbaikan",
        "STATUS_PENGAJUAN_DIBATALKAN"=>"Dibatalkan",
        "STATUS_PENGAJUAN_DITERIMA"=>"Diterima",
        "STATUS_PENGAJUAN_DIBUAT"=>"Dibuat",
        "STATUS_PENGAJUAN_DIKUMPULKAN"=>"Dikumpulkan",
        "STATUS_PENGAJUAN_DICAIRKAN"=>"Dicairkan",
    ];

    public static function getJenisTransportasiOptions(){
        return self::JENIS_TRANSPORTASI_OPTIONS;
    }
    public static function getJenisSuratTugasOptions(){
        return self::JENIS_SURAT_TUGAS_OPTIONS;
    }

}
